#!/usr/bin/env bash

# https://gist.github.com/reegnz/b9e40993d410b75c2d866441add2cb55
# https://paweldu.dev/posts/fzf-live-repl/
# https://github.com/reegnz/jq-zsh-plugin
#
#
#
# USAGE: cat myjson.json | jqr
# USAGE: jqr myjson.json

if [[ -z $1 ]] || [[ $1 == "-" ]]; then
    input=$(mktemp)
    trap "rm -f $input" EXIT
    cat /dev/stdin > $input
else
    input=$1
fi

echo '' \
    | fzf --phony \
          --preview-window='up:90%' \
          --print-query \
          --preview "jq --color-output -r {q} $input"
