#!/bin/bash
JOURNAL_DIR=$HOME/.j
mkdir -p $JOURNAL_DIR

TARGET_DAY=$(date +%Y-%m-%d)
TIME_MARKER=$(date +" ----- %Y-%m-%dT%H:%M:%S")

ENTRY_FILE=$JOURNAL_DIR/$TARGET_DAY.md

echo $TIME_MARKER >> $ENTRY_FILE
nvim "+ normal G $" $ENTRY_FILE
