#!/usr/bin/env bash

# installation instructions
#  python3 -m virtualenv $HOME/.virtualenvs/sqlfmt
#  . $HOME/.virtualenvs/sqlfmt/bin/activate
#  python3 -m pip install sqlparse==0.4.2

## USAGE: pipe a sql query to it and it prints it out formatted
## in vim, select the query text, hit :
## it will fill the boundary syntax in giving you :'<,'>
## then type !sqlfmt so that the selected text is replaced with what is returned by this query
## :'<,'>!sqlfmt

VENVPATH=$HOME/.virtualenvs/sqlfmt

# activate venv just for this thing
source $VENVPATH/bin/activate

# do work
python3 -c 'import sqlparse, sys; print(sqlparse.format(sys.stdin.read(), reindent=True, keyword_case="upper"))' </dev/stdin
